### ISSUE TITLE
Fix the dnscrypt-autonistall to point to Dyne's stuff not dnscrypt.org due to change in project status (install is broken right now without it) 

### ISSUE THREAD

**Issue by tonsimple** [simonclausen/dnscrypt-autoinstall#108]
Basically, modify to reflect the changes that arose due to this:
https://github.com/dyne/dnscrypt-proxy/blob/master/README.markdown

**Comment by AladW** [comment]
So, we have to point to some random person on the internet's repository which lacks releases and valid signatures? (they just removed the minisign instructions from the readme while advertising their project...) 

Better to simply archive this project if upstream dropped dnscrypt. @simonclausen thoughts?

**Comment by simonclausen** [comment]
I have had limited time to keep up with the developments around dnscrypt. But to me it looks like @jedisct1 has split out things a bit and is moving forward with a version 2 of dnscrypt-proxy. The README on both dyne's repo of the original dnscrypt-proxy and Franks version 2 point towards version 1 being archived.

Even though it looks like dyne thought the archiving of dnscrypt-proxy version 1 to be a sign that DNSCrypt itself is being abandoned by Frank, it looks like it's just the specific implementation he's dropping in favor of a never development.

So far it looks like he's also taking care of the installation along with a new way to configure which service(s) you want to use. Which are fundamental reasons for this script to exist.

All in all, I think you make a good point of archiving this project as well. As you can probably tell, I have also not been putting much time into it for a while - this because I don't deploy dnscrypt on linux a lot any longer.

Maybe make it work with dyne's "patched only" dnscrypt-proxy v1 and call it a day?

**Comment by simonclausen** [comment]
Maybe dyne would be interested in taking over dnscrypt-autoinstall, as @tonsimple suggests here: https://github.com/dyne/dnscrypt-proxy/issues/4

**Comment by tvladyslav** [comment]
Hi!
Is there any progress on solving the problem? Pull request https://github.com/simonclausen/dnscrypt-autoinstall/pull/110 fixed the script, so mayme it is worth to merge it?

**Comment by simonclausen** [comment]
Hi @crypto-universe,

Nope - no progress here or replies from @dyne or @jaromil. Tbh, it looks like their fork of dnscrypt-proxy v1 is now abandoned as well.

My clear recommendation is to go with @jedisct1's new [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy), as that covers the original goal of dnscrypt-autoinstall with native functionality.

Without indications of continued work on the forked v1 of dnscrypt-proxy, I would rather have dnscrypt-autoinstall not work out of the box any longer, than point to - and implicitly endorse - something that would probably present a security or privacy risk for someone at some point.

So that's it for now, I'm archiving this repo.

Many thanks to @mk-qi, @gitter-badger, @crypto-universe, @Shnatsel, @null0x0, @sfunk1x, @pysiak, @luqmanulhackim, @theodorerambert, @glitsj16 and especially @AladW and @lucaspetter for contributions, as well as everyone who took the time to report issues and take part in discussions.
