### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by hamariko** [simonclausen/dnscrypt-autoinstall#35]
Hi guys,

Thanks for the great script! Ii have 2 requests:

1. Would it be possible to add an option/entry in the menu to switch to non-encrypted dns without having to uninstall? And back again? Like some sort of pause/resume option.
I sometimes cannot use encrypted dns when I need to connect to a company vpn. I can connect to the vpn server but this does not understand the encrypted dns requests...
2. Is a ppa an idea?

Bye
Hans

**Comment by wxnarwhal** [comment]
The same goes for captive portals.  I've been traveling for months and never considered using encrypted DNS until I was connecting to public access points on a daily basis.  The proxy works brilliantly and I'm very grateful for the work that has gone in to making this so easy to use.  However, so many access points use DNS hijacking to redirect to captive portals where I have to agree to a terms of service before I'm granted internet access.  This of course cannot work with encrypted DNS.  So a quicker toggle action/flag to enable/disable would be a good enhancement.

**Comment by wxnarwhal** [comment]
Sorry, I'm not experiences with Github.  I noticed after posting that this topic is closed.  Since these comments are public and others might be searching for a solution to this same problem I will include my solution here.  I am using Linux Mint so I took the Debian method of updating /etc/resolv.conf directly from dnscrypt-autoinstall.sh.  I simply created the following two bash scripts to enable or disable dnscrypt as required.

disable-dnscrypt.sh
    
    #!/bin/bash
    
    chattr -i /etc/resolv.conf
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "nameserver 8.8.4.4" >> /etc/resolv.conf
    chattr +i /etc/resolv.conf

enable-dnscrypt.sh
    
    #!/bin/bash
    
    chattr -i /etc/resolv.conf
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    echo "nameserver 127.0.0.2" >> /etc/resolv.conf
    chattr +i /etc/resolv.conf

**Comment by AladW** [comment]
This was implemented a while ago with the "None" option.
