### ISSUE TITLE
Get and parse dnscrypt-resolvers.csv instead of hardcoding options into the script

### ISSUE THREAD

**Issue by simonclausen** [simonclausen/dnscrypt-autoinstall#62]
This would require a big rework of the scripts, but I'm clearing my head: the idea is now here in black on white,

**Comment by lucaspetter** [comment]
Yes, that's a big rework, but it makes sense to do it.

No need for the script to actually *parse* [dnscrypt-resolvers.csv](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) because dnscrypt-proxy already parses with the `--resolvers-list` flag.

eg. The current way, manually specifying each parameter:
```
dnscrypt-proxy --daemonize --ephemeral-keys --user=dnscrypt --local-address=127.0.0.1 --resolver-address=77.66.84.233 --provider-name=2.dnscrypt-cert.resolver2.dnscrypt.eu --provider-key=3748:5585:E3B9:D088:FD25:AD36:B037:01F5:520C:D648:9E9A:DD52:1457:4955:9F0A:9955
dnscrypt-proxy --daemonize --ephemeral-keys --user=dnscrypt --local-address=127.0.0.2 --resolver-address=176.56.237.171 --provider-name=2.dnscrypt-cert.resolver1.dnscrypt.eu --provider-key=67C0:0F2C:21C5:5481:45DD:7CB4:6A27:1AF2:EB96:9931:40A3:09B6:2B8D:1653:1185:9C66
```

eg. With --resolvers-list=dnscrypt-resolvers.csv:
```
dnscrypt-proxy --daemonize --ephemeral-keys --user=dnscrypt --local-address=127.0.0.1 --resolvers-list="/path/to/dnscrypt-resolvers.csv" --resolver-name="dnscrypt.eu-dk"
dnscrypt-proxy --daemonize --ephemeral-keys --user=dnscrypt --local-address=127.0.0.1 --resolvers-list="/path/to/dnscrypt-resolvers.csv" --resolver-name="dnscrypt.eu-nl"
```

When downloading dnscrypt-resolvers.csv, the script should also verify the PGP signature, [dnscrypt-resolvers.csv.sig](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv.sig).

Another reason it would be good to rework things is so users can switch between providers fully offline, instead of connecting to this GitHub repo to download the init-script.sh files every time. There's currently an issue where, if your DNSCrypt providers go down, you have no way of resolving github.com's IP and therefore can't connect to get a new init-script for a different provider; in this case, you're stuck without DNS unless you uninstall or wait for the provider to come back up or manually change to a different provider. (I've had this happen a few times recently.)

**Comment by simonclausen** [comment]
Interesting. I've never thought of that as a scenario - not being able to switch providers, if the current one is down. Good catch.

Anyway, the reason I'm thinking it needs to be parsed is because we want to pick out some information to display to the user (Full name, description, location for instance), but also the name to pass to dnscrypt-proxy when running it.

Also, there may be an interesting problem in how to handle multiple resolvers by one provider. ATM, we pull init scripts that are configured to use multiple resolvers by one provider. How should this be done and how should the user be presented with a choice? I'm thinking pulling groups via i.e. dnscrypteu-*, getting the full name/description from one, and presenting that to the user and using the names from the resolver list to configure the dnscrypt-proxy service.

Maybe ask Frank if it would make sense to have a "provider group" column of some sorts in the resolver list to support doing stuff like this.

**Comment by lucaspetter** [comment]
Regarding multiple resolvers by one provider:

If we group resolvers based on provider, how would this apply to the OpenNIC resolvers? There are 27 of them in the .csv located all over the world. Users should be able to pick 2 that are closest to their locations, rather than using all 27 and not optimized for location. Also, for "solitary" resolvers like Soltysiak or okTurtles, which are the only ones by their providers, would users be stuck with only 1 resolver and no secondary resolver? It would be good if every user could configure 2 resolvers in case one goes down.

Perhaps we could show users the full list of all resolvers from the .csv file and let them pick one as their primary resolver, then show the list again so they can pick a secondary resolver. This would allow for the most control over which providers are used.

Then, for users who just want a simple solution without having to look through the entire list, it could default to DNSCrypt.eu or pick 2 resolvers at random. ([dnscrypt-osxclient](https://github.com/alterstep/dnscrypt-osxclient/) by default picks 1 at random unless the user selects a resolver from the list.)

**Comment by simonclausen** [comment]
Grouping by provider and/or location and/or features should probably be considered. Some people may not trust one provider over another, others may only care for certain feature sets. Location is more or less a given, because of latency and CDN issues.

**Comment by AladW** [comment]
We could simply use select+awk:
```
$ select foo in $(awk -F',' '{print $1}' dnscrypt-resolvers.csv); do break; done
 1) Name		    24) d0wn-de-ns1		47) fvz-anytwo
 2) 4armed		    25) d0wn-de-ns2		48) fvz-rec-at-vie-01
 3) cisco		    26) d0wn-dk-ns1		49) fvz-rec-ca-tor-01
 4) cisco-familyshield	    27) d0wn-fr-ns2		50) fvz-rec-ca-tor-01-ipv6
 5) cisco-ipv6		    28) d0wn-gr-ns1		51) fvz-rec-de-fra-01
 6) cisco-port53	    29) d0wn-is-ns1		52) fvz-rec-gb-brs-01
 7) cloudns-syd		    30) d0wn-it-ns1		53) fvz-rec-gb-lon-01
 8) cs-cawest		    31) d0wn-lv-ns1		54) fvz-rec-gb-lon-03
 9) cs-cfi		    32) d0wn-md-ns1		55) fvz-rec-hk-ztw-01
10) cs-cfii		    33) d0wn-nl-ns1		56) fvz-rec-ie-du-01
11) cs-ch		    34) d0wn-nl-ns2		57) fvz-rec-nz-akl-01
12) cs-de		    35) d0wn-random-ns1		58) fvz-rec-nz-akl-01-ipv6
13) cs-fr		    36) d0wn-random-ns2		59) ipredator
14) cs-fr2		    37) d0wn-ru-ns1		60) ns0.dnscrypt.is
15) cs-rome		    38) d0wn-sg-ns1		61) okturtles
16) cs-useast		    39) d0wn-tz-ns1		62) opennic-tumabox
17) cs-usnorth		    40) d0wn-ua-ns1		63) ovpnse
18) cs-ussouth		    41) dnscrypt.eu-dk		64) resolv-east
19) cs-ussouth2		    42) dnscrypt.eu-dk-ipv6	65) resolv-west
20) cs-uswest		    43) dnscrypt.eu-nl		66) soltysiak
21) cs-uswest2		    44) dnscrypt.eu-nl-ipv6	67) soltysiak-ipv6
22) d0wn-bg-ns1		    45) dnscrypt.org-fr		68) spdysync
23) d0wn-cz-ns1		    46) fvz-anyone		69) yandex
```
Since the numbers match, users could look up their preferred provider on-line, and then select it in the script.

**Comment by simonclausen** [comment]
I hadn't noticed that "Name" resolver (#1 on the list), nice.

Bad joke aside, that looks good!

**Comment by AladW** [comment]
I've decided to go with a tab-separated list:
```
 1) None                          (Regular, unencrypted DNS)
 2) 4armed                        (4ARMED)
 3) cisco                         (Cisco OpenDNS)
 4) cisco-familyshield            (Cisco OpenDNS with FamilyShield)
 5) cisco-ipv6                    (Cisco OpenDNS over IPv6)
 6) cisco-port53                  (Cisco OpenDNS backward compatibility port 53)
 7) cloudns-syd                   (CloudNS Sydney)
 8) cs-cawest                     (CS Canada west DNSCrypt server)
 9) cs-cfi                        (CS cryptofree France DNSCrypt server)
10) cs-cfii                       (CS secondary cryptofree France DNSCrypt server)
11) cs-ch                         (CS Switzerland DNSCrypt server)
12) cs-de                         (CS Germany DNSCrypt server)
13) cs-fr                         (CS France DNSCrypt server)
14) cs-fr2                        (CS secondary France DNSCrypt server)
15) cs-rome                       (CS Italy DNSCrypt server)
16) cs-useast                     (CS New York City NY US DNSCrypt server)
17) cs-usnorth                    (CS Chicago IL US DNSCrypt server)
18) cs-ussouth                    (CS Dallas TX US DNSCrypt server)
19) cs-ussouth2                   (CS Atlanta GA US DNSCrypt server)
20) cs-uswest                     (CS Seattle WA US DNSCrypt server)
21) cs-uswest2                    (CS Las Vegas NV US DNSCrypt server)
22) d0wn-bg-ns1                   (OpenNIC Resolver Bulgaria 01 - d0wn)
23) d0wn-cz-ns1                   (OpenNIC Resolver Czech Republic 01 - d0wn)
24) d0wn-de-ns1                   (OpenNIC Resolver Germany 01 - d0wn)
25) d0wn-de-ns2                   (OpenNIC Resolver Germany 02 - d0wn)
26) d0wn-dk-ns1                   (OpenNIC Resolver Denmark 01 - d0wn)
27) d0wn-fr-ns2                   (OpenNIC Resolver France 02 - d0wn)
28) d0wn-gr-ns1                   (OpenNIC Resolver Greece 01 - d0wn)
29) d0wn-is-ns1                   (OpenNIC Resolver Iceland 01 - d0wn)
30) d0wn-it-ns1                   (OpenNIC Resolver Italy 01 - d0wn)
31) d0wn-lv-ns1                   (OpenNIC Resolver Latvia 01 - d0wn)
32) d0wn-md-ns1                   (OpenNIC Resolver Moldova 01 - d0wn)
33) d0wn-nl-ns1                   (OpenNIC Resolver Netherlands 01 - d0wn)
34) d0wn-nl-ns2                   (OpenNIC Resolver Netherlands 02 - d0wn)
35) d0wn-random-ns1               (DNSCrypt Randomizer 01 - d0wn)
36) d0wn-random-ns2               (DNSCrypt Randomizer 02 - d0wn)
37) d0wn-ru-ns1                   (OpenNIC Resolver Russia 01 - d0wn)
38) d0wn-sg-ns1                   (OpenNIC Resolver Singapore 01 - d0wn)
39) d0wn-tz-ns1                   (OpenNIC Resolver Tanzania 01 - d0wn)
40) d0wn-ua-ns1                   (OpenNIC Resolver Ukraine 01 - d0wn)
41) dnscrypt.eu-dk                (DNSCrypt.eu Denmark)
42) dnscrypt.eu-dk-ipv6           (DNSCrypt.eu Denmark over IPv6)
43) dnscrypt.eu-nl                (DNSCrypt.eu Holland)
44) dnscrypt.eu-nl-ipv6           (DNSCrypt.eu Holland over IPv6)
45) dnscrypt.org-fr               (DNSCrypt.org France)
46) fvz-anyone                    (Primary OpenNIC Anycast DNS Resolver)
47) fvz-anytwo                    (Secondary OpenNIC Anycast DNS Resolver)
48) fvz-rec-at-vie-01             ("opennic-fvz-rec-at-vie-01 in Vienna)
49) fvz-rec-ca-tor-01             ("opennic-fvz-rec-ca-tor-01 in Toronto)
50) fvz-rec-ca-tor-01-ipv6        ("opennic-fvz-rec-ca-tor-01 in Toronto)
51) fvz-rec-de-fra-01             ("opennic-fvz-rec-de-fra-01 in Frankfurt)
52) fvz-rec-gb-brs-01             ("opennic-fvz-rec-gb-brs-01 in Bristol)
53) fvz-rec-gb-lon-01             ("opennic-fvz-rec-gb-lon-01 in London)
54) fvz-rec-gb-lon-03             ("opennic-fvz-rec-gb-lon-03 in London)
55) fvz-rec-hk-ztw-01             ("opennic-fvz-rec-hk-ztw-01 in Tsuen Wan)
56) fvz-rec-ie-du-01              ("opennic-fvz-rec-ie-du-01 in Dublin)
57) fvz-rec-nz-akl-01             ("opennic-fvz-rec-nz-akl-01 in Auckland)
58) fvz-rec-nz-akl-01-ipv6        ("opennic-fvz-rec-nz-akl-01 in Auckland)
59) ipredator                     (Ipredator.se Server)
60) ns0.dnscrypt.is               ("ns0.dnscrypt.is in Reykjavík)
61) okturtles                     (okTurtles)
62) opennic-tumabox               (TumaBox)
63) ovpnse                        (OVPN.se Integritet AB)
64) resolv-east                   (Resolv East)
65) resolv-west                   (Resolv West)
66) soltysiak                     (Soltysiak)
67) soltysiak-ipv6                (Soltysiak over IPv6)
68) spdysync                      (SpdySync)
69) yandex                        (Yandex)
```
Please continue discussion in #64
